apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: cp4a-springboot-pipeline
spec:
  resources:
    - name: source
      type: git
    - name: infra
      type: git
  tasks:
    - name: build
      taskRef:
        name: cp4a-task-build
      resources:
        inputs:
          - name: source
            resource: source
      params:
        - name: APP_NAME
          value: helloboot
    - name: deploy
      taskRef:
        name: cp4a-task-deploy
      resources:
        inputs:
          - name: infra
            resource: infra
      params:
        - name: APP_NAME
          value: helloboot
      runAfter:
        - build