apiVersion: v1
kind: Secret
metadata:
  name: git-infra-secret
  annotations:
    tekton.dev/git-0: https://github.ibm.com
type: kubernetes.io/basic-auth
stringData:
  username: Omar-Gaye
  password: 821bfc8d32d295fa0b8eb085a7cfdacefebd640b