apiVersion: v1
kind: Secret
metadata:
  name: git-infra-secret
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: ogaye-ibm
  password: 18e30b8aa3bcb650f79cd6cf24068b2f2f1c56af